import { test, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";

import config from "../config/notification.config.js";
import { DeliveryStatus, NotificationEvents, Channels } from "../config/events.js";

/**
 * End-to-end wiring for MSG91: a domain event goes through the real workflow,
 * the real Dispatcher and the real provider, with only the MSG91 HTTP call
 * stubbed. The unit tests hand the provider a context they build themselves —
 * this proves the DISPATCHER supplies one of the right shape, which is what
 * actually breaks in production when the wiring is wrong.
 *
 * ORDER MATTERS: the SMS channel is switched to msg91 and the template ids are
 * set BEFORE anything imports the provider registry, because getProvider()
 * caches one adapter per channel for the life of the process. Node runs each
 * test file in its own process, so this is contained to this file.
 */
config.providers[Channels.SMS] = "msg91";
process.env.MSG91_OTP_TEMPLATE_ID = "6a7359294976ac1599096612";
process.env.MSG91_REMINDER_TEMPLATE_ID = "6a735a25ab93306df0082913";
delete process.env.MSG91_BOOKING_TEMPLATE_ID;
// OTP ships BLOCKED until its MSG91 template is fixed (config/msg91Templates.js).
// These cases are about ENGINE WIRING, so they run against a resolved mapping —
// the block itself is covered in msg91.test.js.
process.env.MSG91_OTP_VARS = "otp=otp,company=companyName";

const { Dispatcher } = await import("../core/Dispatcher.js");
const { NotificationService } = await import("../core/NotificationService.js");
const { JsonNotificationRepository } = await import("../repository/NotificationRepository.js");
const { getProvider } = await import("../providers/index.js");
const { defaultContext } = await import("../workflows/registry.js");

const repo = new JsonNotificationRepository();
const fakeQueue = { enqueue() {} };
const dispatcher = new Dispatcher({ repository: repo, queue: fakeQueue });

const origFetch = globalThis.fetch;
const origMsg91 = { ...config.msg91 };

const uid = (name) => `RC-NTF-M91-${name}-${Date.now()}-${Math.random().toString(36).slice(2)}`;

before(() => {
  Object.assign(config.msg91, {
    authKey: "test-auth-key",
    senderId: "KVROCR",
    baseUrl: "https://control.msg91.com",
    defaultCountryCode: "91",
    timeoutMs: 200,
  });
});
after(() => {
  globalThis.fetch = origFetch;
  Object.assign(config.msg91, origMsg91);
});
beforeEach(() => {
  globalThis.fetch = origFetch;
});

/** Stub MSG91's HTTP endpoint; records the outgoing request. */
function stubFetch({ status = 200, json = { type: "success", request_id: "req_1" }, calls } = {}) {
  globalThis.fetch = async (url, opts) => {
    calls?.push({ url, opts });
    return { ok: status >= 200 && status < 300, status, json: async () => json };
  };
}

/** Create a QUEUED SMS record the way NotificationService would. */
async function queueSms(event, payload, extra = {}) {
  const id = uid("rec");
  await repo.create({
    id,
    event,
    channel: Channels.SMS,
    recipient: payload.phone,
    status: DeliveryStatus.QUEUED,
    maxAttempts: 1,
    payload: defaultContext(payload),
    ...extra,
  });
  return id;
}

test("the SMS channel really resolves to the MSG91 adapter here", () => {
  assert.equal(getProvider(Channels.SMS).name, "msg91-sms");
});

// -------------------- OTP, through the whole engine --------------------
test("OTP event -> Dispatcher -> MSG91: correct template, the app's own OTP, record SENT", async () => {
  const calls = [];
  stubFetch({ calls });

  const id = await queueSms(
    NotificationEvents.OTP_REQUESTED,
    { phone: "9876543210", name: "Arjun", otp: "482913" },
    { correlationId: "corr-xyz" }
  );
  await dispatcher.process(id);

  // The provider was actually called, with the right template and variables.
  assert.equal(calls.length, 1, "exactly one MSG91 request");
  const sent = JSON.parse(calls[0].opts.body);
  assert.equal(sent.flow_id, "6a7359294976ac1599096612");
  assert.equal(sent.template_id, undefined, "template_id must never be sent");
  assert.equal(sent.sender, "KVROCR");
  assert.equal(sent.recipients[0].mobiles, "919876543210");
  assert.equal(sent.recipients[0].otp, "482913", "the OTP generated by the app is passed through");

  // No rendered SMS prose is transmitted — MSG91 renders the approved content.
  assert.ok(!calls[0].opts.body.includes("verification code"));

  const rec = await repo.findById(id);
  // SUBMITTED, not SENT — MSG91 only confirmed acceptance of the request.
  assert.equal(rec.status, DeliveryStatus.SUBMITTED);
  assert.equal(rec.provider, "msg91-sms");
  assert.equal(rec.attempts, 1);
  assert.equal(rec.providerResponse.providerMessageId, "req_1");
});

// -------------------- reminder, through the whole engine --------------------
test("reminder event -> Dispatcher -> MSG91: reminder template with trip variables", async () => {
  const calls = [];
  stubFetch({ calls });

  const id = await queueSms(NotificationEvents.TRIP_REMINDER, {
    phone: "9876543210",
    bookingId: "RC-BK-77",
    fromDate: "12 Aug 2026",
    item: "Innova Crysta",
    from: "Chennai",
    driver: "Ravi",
  });
  await dispatcher.process(id);

  const sent = JSON.parse(calls[0].opts.body);
  assert.equal(sent.flow_id, "6a735a25ab93306df0082913");
  assert.deepEqual(sent.recipients[0], {
    mobiles: "919876543210",
    bookingId: "RC-BK-77",
    tripDate: "12 Aug 2026",
    vehicle: "Innova Crysta",
    pickup: "Chennai",
    driver: "Ravi",
  });
  assert.equal((await repo.findById(id)).status, DeliveryStatus.SUBMITTED);
});

// -------------------- OTP block, end to end --------------------
test("with the mapping unresolved, an OTP event dead-letters instead of sending", async () => {
  const saved = process.env.MSG91_OTP_VARS;
  delete process.env.MSG91_OTP_VARS; // shipped (blocked) state
  let httpCalled = false;
  globalThis.fetch = async () => {
    httpCalled = true;
    return { ok: true, status: 200, json: async () => ({ type: "success", message: "x" }) };
  };
  try {
    const id = await queueSms(NotificationEvents.OTP_REQUESTED, {
      phone: "9876543210",
      otp: "482913",
    });
    await dispatcher.process(id);

    assert.equal(httpCalled, false, "no malformed OTP may reach MSG91");
    const rec = await repo.findById(id);
    assert.equal(rec.status, DeliveryStatus.DEAD_LETTER);
    assert.match(rec.error, /UNRESOLVED/);
    // The reason is durable on the record, so ops can see WHY without the logs.
    assert.match(rec.error, /MSG91_OTP_VARS/);
  } finally {
    if (saved !== undefined) process.env.MSG91_OTP_VARS = saved;
  }
});

// -------------------- booking: fails safe, terminally --------------------
test("booking event dead-letters immediately instead of sending unapproved content", async () => {
  let httpCalled = false;
  globalThis.fetch = async () => {
    httpCalled = true;
    return { ok: true, status: 200, json: async () => ({ type: "success", request_id: "x" }) };
  };

  const id = await queueSms(NotificationEvents.BOOKING_CONFIRMED, {
    phone: "9876543210",
    bookingId: "RC-BK-1",
    fare: 4500,
  });
  await dispatcher.process(id);

  assert.equal(httpCalled, false, "nothing unapproved may reach MSG91");
  const rec = await repo.findById(id);
  // Non-retryable => straight to dead-letter, no retry storm, visible to ops.
  assert.equal(rec.status, DeliveryStatus.DEAD_LETTER);
  assert.match(rec.error, /MSG91_BOOKING_TEMPLATE_ID/);
});

test("an SMS event with no approved template also dead-letters, never falls back", async () => {
  let httpCalled = false;
  globalThis.fetch = async () => {
    httpCalled = true;
    return { ok: true, status: 200, json: async () => ({ type: "success", request_id: "x" }) };
  };

  const id = await queueSms(NotificationEvents.PAYMENT_SUCCESSFUL, {
    phone: "9876543210",
    bookingId: "RC-BK-2",
  });
  await dispatcher.process(id);

  assert.equal(httpCalled, false);
  const rec = await repo.findById(id);
  assert.equal(rec.status, DeliveryStatus.DEAD_LETTER);
  assert.match(rec.error, /no DLT-approved MSG91 template is mapped/);
});

// -------------------- transient failures still retry --------------------
test("a 503 from MSG91 is retried by the existing engine, not dead-lettered", async () => {
  stubFetch({ status: 503, json: { message: "unavailable" } });

  const id = await queueSms(NotificationEvents.OTP_REQUESTED, {
    phone: "9876543210",
    otp: "482913",
  });
  // maxAttempts 2 so the first failure schedules a retry rather than exhausting.
  await repo.update(id, { maxAttempts: 2 });
  await dispatcher.process(id);

  const rec = await repo.findById(id);
  assert.equal(rec.status, DeliveryStatus.FAILED, "retryable failure stays retryable");
  assert.ok(rec.nextAttemptAt, "a backoff was scheduled by the existing retry engine");
});

// -------------------- unrelated channels are unaffected --------------------
test("booking SMS being unavailable does not stop the booking's email/WhatsApp", async () => {
  const service = new NotificationService({ repository: repo, queue: fakeQueue, dispatcher });
  const created = await service.handleEvent({
    event: NotificationEvents.BOOKING_CONFIRMED,
    eventId: uid("evt"),
    payload: {
      bookingId: uid("bk"),
      email: "customer@test.local",
      phone: "9876543210",
      name: "Arjun",
    },
    actor: "test",
  });

  const channels = created.map((r) => r.channel);
  assert.ok(channels.includes(Channels.EMAIL), "email must still be queued");
  assert.ok(channels.includes(Channels.WHATSAPP), "whatsapp must still be queued");
});
